version: "3"
services:
  fireshare:
    container_name: fireshare
    image: risedsky/fireshare:latest
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./dev_root/fireshare_data:/data
      - ./dev_root/fireshare_processed:/processed
      - ./dev_root/fireshare_videos:/videos
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - SECRET_KEY=replace_this_with_some_random_string
      - MINUTES_BETWEEN_VIDEO_SCANS=5
      - PUID=1001
      - PGID=1001
